"""
Unified ABI coverage check: compare generated exports vs official introspect.

This script performs three coverage checks for official_app_337:

  1) Functions vs introspect:
       - A: functions_introspect_like.json (FUNCTIONS from official introspect)
       - C: wrapper_exports_funcs.json (names generated by gen_funcs + gen_structs)
       - Scope: only prefixes mj_/mju_/mjs_/mjd_

  2) Struct pointers vs introspect:
       - A: structs_introspect_like.json (mjModel/mjData pointer fields)
       - C: mjwf_*_ptr symbols in mjwf_abi_structs.c
       - Require: every pointer field in mjModel/mjData has at least one
         corresponding mjwf_<base>_ptr export, where <base> comes from
         gen_structs.default_pointer_name().

  3) Enums vs introspect:
       - A: enums_introspect_like.json
       - C: enums.json (generated by gen_enums.py)
       - Scope: enum names; values are not checked here.

The goal is to ensure that our generated ABI surface stays aligned with the
official introspect tables, without re-scanning headers or maintaining manual
whitelists.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Sequence, Set, Tuple


ALLOWED_FUNC_PREFIXES: Tuple[str, ...] = ("mj_", "mju_", "mjs_", "mjd_")


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _load_json(path: Path) -> Mapping[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# Struct pointer coverage
# ---------------------------------------------------------------------------

@dataclass
class PointerField:
    struct: str
    field: str
    type_kind: str
    inner_kind: str
    inner_name: str | None


def load_introspect_structs(path: Path) -> Dict[str, List[PointerField]]:
    data = _load_json(path)
    structs = data.get("structs", {}) or {}
    out: Dict[str, List[PointerField]] = {}
    for struct_name, s in structs.items():
        fields = []
        for f in s.get("fields", []) or []:
            t = f.get("type") or {}
            kind = t.get("kind")
            if kind != "PointerType":
                continue
            inner = t.get("inner") or {}
            fields.append(
                PointerField(
                    struct=str(struct_name),
                    field=str(f.get("name") or ""),
                    type_kind=str(kind),
                    inner_kind=str(inner.get("kind") or ""),
                    inner_name=inner.get("name"),
                )
            )
        out[str(struct_name)] = fields
    return out


def load_pointer_exports(exports_c: Path) -> Set[str]:
    src = exports_c.read_text(encoding="utf-8")
    names = set(re.findall(r"\bmjwf_([A-Za-z0-9_]+)_ptr\b", src))
    return names


def check_struct_pointers(
    abi_dir: Path, repo_root: Path
) -> Tuple[List[Tuple[str, str, str]], List[str]]:
    """Return (missing_ptr_exports, extra_unmatched_basenames)."""
    # Import pointer naming from the current struct generator.
    if str(repo_root) not in sys.path:
        sys.path.insert(0, str(repo_root))
    from abi_exports.gen_structs import (  # type: ignore
        default_pointer_name,
    )

    structs_json = abi_dir / "structs_introspect_like.json"
    exports_c = repo_root / "app" / "337" / "src" / "mjwf_abi_structs.c"

    structs = load_introspect_structs(structs_json)
    export_names = load_pointer_exports(exports_c)

    missing: List[Tuple[str, str, str]] = []
    extra_unmatched: Set[str] = set(export_names)

    for struct_name in ("mjModel", "mjData"):
        for pf in structs.get(struct_name, []):
            if not pf.field:
                continue
            expected_base = default_pointer_name(struct_name, pf.field)
            if not expected_base:
                continue
            expected_symbol = f"mjwf_{expected_base}_ptr"
            if expected_base in extra_unmatched:
                extra_unmatched.remove(expected_base)
            if expected_base not in export_names:
                missing.append((struct_name, pf.field, expected_symbol))

    return missing, sorted(extra_unmatched)


# ---------------------------------------------------------------------------
# Function coverage
# ---------------------------------------------------------------------------

def _is_core_func(name: str) -> bool:
    return name.startswith(ALLOWED_FUNC_PREFIXES)


def load_introspect_functions(path: Path) -> Set[str]:
    data = _load_json(path)
    funcs = data.get("functions", []) or []
    names = {str(f.get("name")) for f in funcs if f.get("name")}
    return {n for n in names if _is_core_func(n)}


def load_wrapped_functions(manifest_path: Path) -> Set[str]:
    data = _load_json(manifest_path)
    names = data.get("names", []) or []
    # manifest names are base names used by gen_funcs/gen_structs; functions
    # share the same name as the underlying C symbol.
    return {str(n) for n in names if _is_core_func(str(n))}


def check_functions(abi_dir: Path) -> Tuple[List[str], List[str]]:
    """Return (missing_wrappers, extra_wrappers)."""
    introspect_path = abi_dir / "functions_introspect_like.json"
    manifest_path = abi_dir / "wrapper_exports_funcs.json"

    a_names = load_introspect_functions(introspect_path)
    c_names = load_wrapped_functions(manifest_path)

    missing_wrappers = sorted(a_names - c_names)
    extra_wrappers = sorted(c_names - a_names)
    return missing_wrappers, extra_wrappers


# ---------------------------------------------------------------------------
# Enum coverage
# ---------------------------------------------------------------------------

def load_introspect_enums(path: Path) -> Set[str]:
    data = _load_json(path)
    enums = data.get("enums", {}) or {}
    return {str(name) for name in enums.keys()}


def load_generated_enums(path: Path) -> Set[str]:
    data = _load_json(path)
    enums = data.get("enums", {}) or {}
    return {str(name) for name in enums.keys()}


def check_enums(abi_dir: Path) -> Tuple[List[str], List[str]]:
    """Return (missing_enums, extra_enums)."""
    introspect_path = abi_dir / "enums_introspect_like.json"
    generated_path = abi_dir / "enums.json"

    a_enums = load_introspect_enums(introspect_path)
    c_enums = load_generated_enums(generated_path)

    missing = sorted(a_enums - c_enums)
    extra = sorted(c_enums - a_enums)
    return missing, extra


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _print_section(title: str) -> None:
    print()
    print("=" * len(title))
    print(title)
    print("=" * len(title))


def _print_list(label: str, items: Sequence[str]) -> None:
    print(f"\n-- {label} --")
    if not items:
        print("  (none)")
        return
    for x in items:
        print(f"  {x}")


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Check functions / structs / enums coverage of generated exports "
            "against official introspect JSON."
        )
    )
    parser.add_argument(
        "--version",
        default="3.3.7",
        help="MuJoCo version whose ABI dir to inspect (default: 3.3.7).",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)

    repo_root = _repo_root()
    abi_dir = repo_root / "dist" / args.version / "abi"

    # 1) Functions
    missing_funcs, extra_funcs = check_functions(abi_dir)
    _print_section("[1] Functions vs introspect (core prefixes only)")
    _print_list("1.1 missing wrappers for introspect functions", missing_funcs)
    _print_list("1.2 wrapped functions not present in introspect", extra_funcs)

    # 2) Struct pointers
    missing_ptrs, extra_ptr_bases = check_struct_pointers(abi_dir, repo_root)
    _print_section("[2] Struct pointers vs introspect (mjModel/mjData)")
    if missing_ptrs:
        print("\n-- 2.1 missing pointer exports (struct.field -> symbol) --")
        for struct_name, field, sym in missing_ptrs:
            print(f"  {struct_name}.{field} -> {sym}")
    else:
        print("\n-- 2.1 missing pointer exports (struct.field -> symbol) --")
        print("  (none)")

    _print_list(
        "2.2 pointer exports without direct mjModel/mjData field match (derived/dims/count candidates)",
        [f"{name}_ptr" for name in extra_ptr_bases],
    )

    # 3) Enums
    missing_enums, extra_enums = check_enums(abi_dir)
    _print_section("[3] Enums vs introspect")
    _print_list("3.1 missing enums in enums.json", missing_enums)
    _print_list("3.2 extra enums in enums.json (not in introspect)", extra_enums)

    ok = not (missing_funcs or extra_funcs or missing_ptrs or missing_enums)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
