// AUTO-GENERATED: MuJoCo WASM function wrapper declarations.
// Source: abi_exports/gen_funcs.py
#pragma once

#include <mujoco/mujoco.h>

#ifdef __cplusplus
extern "C" {
#endif

#if defined(__EMSCRIPTEN__)
#  include <emscripten/emscripten.h>
#  define MJWF_API EMSCRIPTEN_KEEPALIVE __attribute__((used, visibility("default")))
#else
#  define MJWF_API __attribute__((used, visibility("default")))
#endif

MJWF_API void mjwf_mj_Euler(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_RungeKutta(const mjModel * m, mjData * d, int N);
MJWF_API int mjwf_mj_addBufferVFS(mjVFS * vfs, const char * name, const void * buffer, int nbuffer);
MJWF_API int mjwf_mj_addContact(const mjModel * m, mjData * d, const mjContact * con);
MJWF_API int mjwf_mj_addFileVFS(mjVFS * vfs, const char * directory, const char * filename);
MJWF_API void mjwf_mj_addM(const mjModel * m, mjData * d, mjtNum * dst, int * rownnz, int * rowadr, int * colind);
MJWF_API void mjwf_mj_angmomMat(const mjModel * m, mjData * d, mjtNum * mat, int body);
MJWF_API void mjwf_mj_applyFT(const mjModel * m, mjData * d, const mjtNum force[3], const mjtNum torque[3], const mjtNum point[3], int body, mjtNum * qfrc_target);
MJWF_API void mjwf_mj_camlight(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_checkAcc(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_checkPos(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_checkVel(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_clearCache(mjCache * cache);
MJWF_API void mjwf_mj_collision(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_comPos(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_comVel(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_compareFwdInv(const mjModel * m, mjData * d);
MJWF_API mjModel * mjwf_mj_compile(mjSpec * s, const mjVFS * vfs);
MJWF_API void mjwf_mj_constraintUpdate(const mjModel * m, mjData * d, const mjtNum * jar, mjtNum cost[1], int flg_coneHessian);
MJWF_API void mjwf_mj_contactForce(const mjModel * m, const mjData * d, int id, mjtNum result[6]);
MJWF_API int mjwf_mj_copyBack(mjSpec * s, const mjModel * m);
MJWF_API mjData * mjwf_mj_copyData(mjData * dest, const mjModel * m, const mjData * src);
MJWF_API mjModel * mjwf_mj_copyModel(mjModel * dest, const mjModel * src);
MJWF_API mjSpec * mjwf_mj_copySpec(const mjSpec * s);
MJWF_API void mjwf_mj_copyState(const mjModel * m, const mjData * src, mjData * dst, int sig);
MJWF_API void mjwf_mj_crb(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_defaultLROpt(mjLROpt * opt);
MJWF_API void mjwf_mj_defaultOption(mjOption * opt);
MJWF_API void mjwf_mj_defaultSolRefImp(mjtNum * solref, mjtNum * solimp);
MJWF_API void mjwf_mj_defaultVFS(mjVFS * vfs);
MJWF_API void mjwf_mj_defaultVisual(mjVisual * vis);
MJWF_API void mjwf_mj_deleteData(mjData * d);
MJWF_API int mjwf_mj_deleteFileVFS(mjVFS * vfs, const char * filename);
MJWF_API void mjwf_mj_deleteModel(mjModel * m);
MJWF_API void mjwf_mj_deleteSpec(mjSpec * s);
MJWF_API void mjwf_mj_deleteVFS(mjVFS * vfs);
MJWF_API void mjwf_mj_differentiatePos(const mjModel * m, mjtNum * qvel, mjtNum dt, const mjtNum * qpos1, const mjtNum * qpos2);
MJWF_API void mjwf_mj_energyPos(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_energyVel(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_extractState(const mjModel * m, const mjtNum * src, int srcsig, mjtNum * dst, int dstsig);
MJWF_API void mjwf_mj_factorM(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_flex(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_forward(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_forwardSkip(const mjModel * m, mjData * d, int skipstage, int skipsensor);
MJWF_API void mjwf_mj_freeLastXML(void);
MJWF_API void mjwf_mj_freeStack(mjData * d);
MJWF_API void mjwf_mj_fullM(const mjModel * m, mjtNum * dst, const mjtNum * M);
MJWF_API void mjwf_mj_fwdAcceleration(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_fwdActuation(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_fwdConstraint(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_fwdKinematics(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_fwdPosition(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_fwdVelocity(const mjModel * m, mjData * d);
MJWF_API mjtNum mjwf_mj_geomDistance(const mjModel * m, const mjData * d, int geom1, int geom2, mjtNum distmax, mjtNum fromto[6]);
MJWF_API mjCache * mjwf_mj_getCache(void);
MJWF_API size_t mjwf_mj_getCacheCapacity(const mjCache * cache);
MJWF_API size_t mjwf_mj_getCacheSize(const mjCache * cache);
MJWF_API const char * mjwf_mj_getPluginConfig(const mjModel * m, int plugin_id, const char * attrib);
MJWF_API void mjwf_mj_getState(const mjModel * m, const mjData * d, mjtNum * state, int sig);
MJWF_API mjtNum mjwf_mj_getTotalmass(const mjModel * m);
MJWF_API const char * mjwf_mj_id2name(const mjModel * m, int type, int id);
MJWF_API void mjwf_mj_implicit(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_initCtrlHistory(const mjModel * m, mjData * d, int id, const mjtNum * times, const mjtNum * values);
MJWF_API void mjwf_mj_initSensorHistory(const mjModel * m, mjData * d, int id, const mjtNum * times, const mjtNum * values, mjtNum phase);
MJWF_API void mjwf_mj_integratePos(const mjModel * m, mjtNum * qpos, const mjtNum * qvel, mjtNum dt);
MJWF_API void mjwf_mj_invConstraint(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_invPosition(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_invVelocity(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_inverse(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_inverseSkip(const mjModel * m, mjData * d, int skipstage, int skipsensor);
MJWF_API int mjwf_mj_isDual(const mjModel * m);
MJWF_API int mjwf_mj_isPyramidal(const mjModel * m);
MJWF_API int mjwf_mj_isSparse(const mjModel * m);
MJWF_API void mjwf_mj_island(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_jac(const mjModel * m, const mjData * d, mjtNum * jacp, mjtNum * jacr, const mjtNum point[3], int body);
MJWF_API void mjwf_mj_jacBody(const mjModel * m, const mjData * d, mjtNum * jacp, mjtNum * jacr, int body);
MJWF_API void mjwf_mj_jacBodyCom(const mjModel * m, const mjData * d, mjtNum * jacp, mjtNum * jacr, int body);
MJWF_API void mjwf_mj_jacDot(const mjModel * m, const mjData * d, mjtNum * jacp, mjtNum * jacr, const mjtNum point[3], int body);
MJWF_API void mjwf_mj_jacGeom(const mjModel * m, const mjData * d, mjtNum * jacp, mjtNum * jacr, int geom);
MJWF_API void mjwf_mj_jacPointAxis(const mjModel * m, mjData * d, mjtNum * jacPoint, mjtNum * jacAxis, const mjtNum point[3], const mjtNum axis[3], int body);
MJWF_API void mjwf_mj_jacSite(const mjModel * m, const mjData * d, mjtNum * jacp, mjtNum * jacr, int site);
MJWF_API void mjwf_mj_jacSubtreeCom(const mjModel * m, mjData * d, mjtNum * jacp, int body);
MJWF_API void mjwf_mj_kinematics(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_loadAllPluginLibraries(const char * directory, mjfPluginLibraryLoadCallback callback);
MJWF_API mjModel * mjwf_mj_loadModel(const char * filename, const mjVFS * vfs);
MJWF_API mjModel * mjwf_mj_loadModelBuffer(const void * buffer, int buffer_sz);
MJWF_API void mjwf_mj_loadPluginLibrary(const char * path);
MJWF_API mjModel * mjwf_mj_loadXML(const char * filename, const mjVFS * vfs, char * error, int error_sz);
MJWF_API void mjwf_mj_local2Global(mjData * d, mjtNum xpos[3], mjtNum xmat[9], const mjtNum pos[3], const mjtNum quat[4], int body, mjtByte sameframe);
MJWF_API void mjwf_mj_makeConstraint(const mjModel * m, mjData * d);
MJWF_API mjData * mjwf_mj_makeData(const mjModel * m);
MJWF_API void mjwf_mj_makeM(const mjModel * m, mjData * d);
MJWF_API mjSpec * mjwf_mj_makeSpec(void);
MJWF_API void mjwf_mj_markStack(mjData * d);
MJWF_API int mjwf_mj_mountVFS(mjVFS * vfs, const char * filepath, const mjpResourceProvider * provider);
MJWF_API void mjwf_mj_mulJacTVec(const mjModel * m, const mjData * d, mjtNum * res, const mjtNum * vec);
MJWF_API void mjwf_mj_mulJacVec(const mjModel * m, const mjData * d, mjtNum * res, const mjtNum * vec);
MJWF_API void mjwf_mj_mulM(const mjModel * m, const mjData * d, mjtNum * res, const mjtNum * vec);
MJWF_API void mjwf_mj_mulM2(const mjModel * m, const mjData * d, mjtNum * res, const mjtNum * vec);
MJWF_API void mjwf_mj_multiRay(const mjModel * m, mjData * d, const mjtNum pnt[3], const mjtNum * vec, const mjtByte * geomgroup, mjtByte flg_static, int bodyexclude, int * geomid, mjtNum * dist, mjtNum * normal, int nray, mjtNum cutoff);
MJWF_API int mjwf_mj_name2id(const mjModel * m, int type, const char * name);
MJWF_API void mjwf_mj_normalizeQuat(const mjModel * m, mjtNum * qpos);
MJWF_API void mjwf_mj_objectAcceleration(const mjModel * m, const mjData * d, int objtype, int objid, mjtNum res[6], int flg_local);
MJWF_API void mjwf_mj_objectVelocity(const mjModel * m, const mjData * d, int objtype, int objid, mjtNum res[6], int flg_local);
MJWF_API mjSpec * mjwf_mj_parse(const char * filename, const char * content_type, const mjVFS * vfs, char * error, int error_sz);
MJWF_API mjSpec * mjwf_mj_parseXML(const char * filename, const mjVFS * vfs, char * error, int error_sz);
MJWF_API mjSpec * mjwf_mj_parseXMLString(const char * xml, const mjVFS * vfs, char * error, int error_sz);
MJWF_API void mjwf_mj_passive(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_printData(const mjModel * m, const mjData * d, const char * filename);
MJWF_API void mjwf_mj_printFormattedData(const mjModel * m, const mjData * d, const char * filename, const char * float_format);
MJWF_API void mjwf_mj_printFormattedModel(const mjModel * m, const char * filename, const char * float_format);
MJWF_API void mjwf_mj_printFormattedScene(const mjvScene * s, const char * filename, const char * float_format);
MJWF_API void mjwf_mj_printModel(const mjModel * m, const char * filename);
MJWF_API void mjwf_mj_printScene(const mjvScene * s, const char * filename);
MJWF_API int mjwf_mj_printSchema(const char * filename, char * buffer, int buffer_sz, int flg_html, int flg_pad);
MJWF_API void mjwf_mj_projectConstraint(const mjModel * m, mjData * d);
MJWF_API mjtNum mjwf_mj_ray(const mjModel * m, const mjData * d, const mjtNum pnt[3], const mjtNum vec[3], const mjtByte * geomgroup, mjtByte flg_static, int bodyexclude, int geomid[1], mjtNum normal[3]);
MJWF_API mjtNum mjwf_mj_rayFlex(const mjModel * m, const mjData * d, int flex_layer, mjtByte flg_vert, mjtByte flg_edge, mjtByte flg_face, mjtByte flg_skin, int flexid, const mjtNum pnt[3], const mjtNum vec[3], int vertid[1], mjtNum normal[3]);
MJWF_API mjtNum mjwf_mj_rayHfield(const mjModel * m, const mjData * d, int geomid, const mjtNum pnt[3], const mjtNum vec[3], mjtNum normal[3]);
MJWF_API mjtNum mjwf_mj_rayMesh(const mjModel * m, const mjData * d, int geomid, const mjtNum pnt[3], const mjtNum vec[3], mjtNum normal[3]);
MJWF_API mjtNum mjwf_mj_readCtrl(const mjModel * m, const mjData * d, int id, mjtNum time, int interp);
MJWF_API const mjtNum * mjwf_mj_readSensor(const mjModel * m, const mjData * d, int id, mjtNum time, mjtNum * result, int interp);
MJWF_API int mjwf_mj_recompile(mjSpec * s, const mjVFS * vfs, mjModel * m, mjData * d);
MJWF_API void mjwf_mj_referenceConstraint(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_resetCallbacks(void);
MJWF_API void mjwf_mj_resetData(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_resetDataDebug(const mjModel * m, mjData * d, unsigned char debug_value);
MJWF_API void mjwf_mj_resetDataKeyframe(const mjModel * m, mjData * d, int key);
MJWF_API void mjwf_mj_rne(const mjModel * m, mjData * d, int flg_acc, mjtNum * result);
MJWF_API void mjwf_mj_rnePostConstraint(const mjModel * m, mjData * d);
MJWF_API int mjwf_mj_saveLastXML(const char * filename, const mjModel * m, char * error, int error_sz);
MJWF_API void mjwf_mj_saveModel(const mjModel * m, const char * filename, void * buffer, int buffer_sz);
MJWF_API int mjwf_mj_saveXML(const mjSpec * s, const char * filename, char * error, int error_sz);
MJWF_API int mjwf_mj_saveXMLString(const mjSpec * s, char * xml, int xml_sz, char * error, int error_sz);
MJWF_API void mjwf_mj_sensorAcc(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_sensorPos(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_sensorVel(const mjModel * m, mjData * d);
MJWF_API size_t mjwf_mj_setCacheCapacity(mjCache * cache, size_t size);
MJWF_API void mjwf_mj_setConst(mjModel * m, mjData * d);
MJWF_API void mjwf_mj_setKeyframe(mjModel * m, const mjData * d, int k);
MJWF_API int mjwf_mj_setLengthRange(mjModel * m, mjData * d, int index, const mjLROpt * opt, char * error, int error_sz);
MJWF_API void mjwf_mj_setState(const mjModel * m, mjData * d, const mjtNum * state, int sig);
MJWF_API void mjwf_mj_setTotalmass(mjModel * m, mjtNum newmass);
MJWF_API mjtSize mjwf_mj_sizeModel(const mjModel * m);
MJWF_API void mjwf_mj_solveM(const mjModel * m, mjData * d, mjtNum * x, const mjtNum * y, int n);
MJWF_API void mjwf_mj_solveM2(const mjModel * m, mjData * d, mjtNum * x, const mjtNum * y, const mjtNum * sqrtInvD, int n);
MJWF_API void * mjwf_mj_stackAllocByte(mjData * d, size_t bytes, size_t alignment);
MJWF_API int * mjwf_mj_stackAllocInt(mjData * d, size_t size);
MJWF_API mjtNum * mjwf_mj_stackAllocNum(mjData * d, size_t size);
MJWF_API int mjwf_mj_stateSize(const mjModel * m, int sig);
MJWF_API void mjwf_mj_step(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_step1(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_step2(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_subtreeVel(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_tendon(const mjModel * m, mjData * d);
MJWF_API void mjwf_mj_transmission(const mjModel * m, mjData * d);
MJWF_API int mjwf_mj_unmountVFS(mjVFS * vfs, const char * filename);
MJWF_API int mjwf_mj_version(void);
MJWF_API const char * mjwf_mj_versionString(void);
MJWF_API void mjwf_mj_warning(mjData * d, int warning, int info);
MJWF_API void mjwf_mjd_inverseFD(const mjModel * m, mjData * d, mjtNum eps, mjtByte flg_actuation, mjtNum * DfDq, mjtNum * DfDv, mjtNum * DfDa, mjtNum * DsDq, mjtNum * DsDv, mjtNum * DsDa, mjtNum * DmDq);
MJWF_API void mjwf_mjd_quatIntegrate(const mjtNum vel[3], mjtNum scale, mjtNum Dquat[9], mjtNum Dvel[9], mjtNum Dscale[3]);
MJWF_API void mjwf_mjd_subQuat(const mjtNum qa[4], const mjtNum qb[4], mjtNum Da[9], mjtNum Db[9]);
MJWF_API void mjwf_mjd_transitionFD(const mjModel * m, mjData * d, mjtNum eps, mjtByte flg_centered, mjtNum * A, mjtNum * B, mjtNum * C, mjtNum * D);
MJWF_API int mjwf_mjs_activatePlugin(mjSpec * s, const char * name);
MJWF_API mjsActuator * mjwf_mjs_addActuator(mjSpec * s, const mjsDefault * def);
MJWF_API mjsBody * mjwf_mjs_addBody(mjsBody * body, const mjsDefault * def);
MJWF_API mjsCamera * mjwf_mjs_addCamera(mjsBody * body, const mjsDefault * def);
MJWF_API mjsDefault * mjwf_mjs_addDefault(mjSpec * s, const char * classname, const mjsDefault * parent);
MJWF_API mjsEquality * mjwf_mjs_addEquality(mjSpec * s, const mjsDefault * def);
MJWF_API mjsExclude * mjwf_mjs_addExclude(mjSpec * s);
MJWF_API mjsFlex * mjwf_mjs_addFlex(mjSpec * s);
MJWF_API mjsFrame * mjwf_mjs_addFrame(mjsBody * body, mjsFrame * parentframe);
MJWF_API mjsJoint * mjwf_mjs_addFreeJoint(mjsBody * body);
MJWF_API mjsGeom * mjwf_mjs_addGeom(mjsBody * body, const mjsDefault * def);
MJWF_API mjsHField * mjwf_mjs_addHField(mjSpec * s);
MJWF_API mjsJoint * mjwf_mjs_addJoint(mjsBody * body, const mjsDefault * def);
MJWF_API mjsKey * mjwf_mjs_addKey(mjSpec * s);
MJWF_API mjsLight * mjwf_mjs_addLight(mjsBody * body, const mjsDefault * def);
MJWF_API mjsMaterial * mjwf_mjs_addMaterial(mjSpec * s, const mjsDefault * def);
MJWF_API mjsMesh * mjwf_mjs_addMesh(mjSpec * s, const mjsDefault * def);
MJWF_API mjsNumeric * mjwf_mjs_addNumeric(mjSpec * s);
MJWF_API mjsPair * mjwf_mjs_addPair(mjSpec * s, const mjsDefault * def);
MJWF_API mjsPlugin * mjwf_mjs_addPlugin(mjSpec * s);
MJWF_API mjsSensor * mjwf_mjs_addSensor(mjSpec * s);
MJWF_API mjsSite * mjwf_mjs_addSite(mjsBody * body, const mjsDefault * def);
MJWF_API mjsSkin * mjwf_mjs_addSkin(mjSpec * s);
MJWF_API mjsTendon * mjwf_mjs_addTendon(mjSpec * s, const mjsDefault * def);
MJWF_API mjsText * mjwf_mjs_addText(mjSpec * s);
MJWF_API mjsTexture * mjwf_mjs_addTexture(mjSpec * s);
MJWF_API mjsTuple * mjwf_mjs_addTuple(mjSpec * s);
MJWF_API void mjwf_mjs_appendFloatVec(mjFloatVecVec * dest, const float * array, int size);
MJWF_API void mjwf_mjs_appendIntVec(mjIntVecVec * dest, const int * array, int size);
MJWF_API void mjwf_mjs_appendString(mjStringVec * dest, const char * text);
MJWF_API mjsActuator * mjwf_mjs_asActuator(mjsElement * element);
MJWF_API mjsBody * mjwf_mjs_asBody(mjsElement * element);
MJWF_API mjsCamera * mjwf_mjs_asCamera(mjsElement * element);
MJWF_API mjsEquality * mjwf_mjs_asEquality(mjsElement * element);
MJWF_API mjsExclude * mjwf_mjs_asExclude(mjsElement * element);
MJWF_API mjsFlex * mjwf_mjs_asFlex(mjsElement * element);
MJWF_API mjsFrame * mjwf_mjs_asFrame(mjsElement * element);
MJWF_API mjsGeom * mjwf_mjs_asGeom(mjsElement * element);
MJWF_API mjsHField * mjwf_mjs_asHField(mjsElement * element);
MJWF_API mjsJoint * mjwf_mjs_asJoint(mjsElement * element);
MJWF_API mjsKey * mjwf_mjs_asKey(mjsElement * element);
MJWF_API mjsLight * mjwf_mjs_asLight(mjsElement * element);
MJWF_API mjsMaterial * mjwf_mjs_asMaterial(mjsElement * element);
MJWF_API mjsMesh * mjwf_mjs_asMesh(mjsElement * element);
MJWF_API mjsNumeric * mjwf_mjs_asNumeric(mjsElement * element);
MJWF_API mjsPair * mjwf_mjs_asPair(mjsElement * element);
MJWF_API mjsPlugin * mjwf_mjs_asPlugin(mjsElement * element);
MJWF_API mjsSensor * mjwf_mjs_asSensor(mjsElement * element);
MJWF_API mjsSite * mjwf_mjs_asSite(mjsElement * element);
MJWF_API mjsSkin * mjwf_mjs_asSkin(mjsElement * element);
MJWF_API mjsTendon * mjwf_mjs_asTendon(mjsElement * element);
MJWF_API mjsText * mjwf_mjs_asText(mjsElement * element);
MJWF_API mjsTexture * mjwf_mjs_asTexture(mjsElement * element);
MJWF_API mjsTuple * mjwf_mjs_asTuple(mjsElement * element);
MJWF_API mjsElement * mjwf_mjs_attach(mjsElement * parent, const mjsElement * child, const char * prefix, const char * suffix);
MJWF_API mjsFrame * mjwf_mjs_bodyToFrame(mjsBody * * body);
MJWF_API void mjwf_mjs_defaultActuator(mjsActuator * actuator);
MJWF_API void mjwf_mjs_defaultBody(mjsBody * body);
MJWF_API void mjwf_mjs_defaultCamera(mjsCamera * camera);
MJWF_API void mjwf_mjs_defaultEquality(mjsEquality * equality);
MJWF_API void mjwf_mjs_defaultFlex(mjsFlex * flex);
MJWF_API void mjwf_mjs_defaultFrame(mjsFrame * frame);
MJWF_API void mjwf_mjs_defaultGeom(mjsGeom * geom);
MJWF_API void mjwf_mjs_defaultHField(mjsHField * hfield);
MJWF_API void mjwf_mjs_defaultJoint(mjsJoint * joint);
MJWF_API void mjwf_mjs_defaultKey(mjsKey * key);
MJWF_API void mjwf_mjs_defaultLight(mjsLight * light);
MJWF_API void mjwf_mjs_defaultMaterial(mjsMaterial * material);
MJWF_API void mjwf_mjs_defaultMesh(mjsMesh * mesh);
MJWF_API void mjwf_mjs_defaultNumeric(mjsNumeric * numeric);
MJWF_API void mjwf_mjs_defaultOrientation(mjsOrientation * orient);
MJWF_API void mjwf_mjs_defaultPair(mjsPair * pair);
MJWF_API void mjwf_mjs_defaultPlugin(mjsPlugin * plugin);
MJWF_API void mjwf_mjs_defaultSensor(mjsSensor * sensor);
MJWF_API void mjwf_mjs_defaultSite(mjsSite * site);
MJWF_API void mjwf_mjs_defaultSkin(mjsSkin * skin);
MJWF_API void mjwf_mjs_defaultSpec(mjSpec * spec);
MJWF_API void mjwf_mjs_defaultTendon(mjsTendon * tendon);
MJWF_API void mjwf_mjs_defaultText(mjsText * text);
MJWF_API void mjwf_mjs_defaultTexture(mjsTexture * texture);
MJWF_API void mjwf_mjs_defaultTuple(mjsTuple * tuple);
MJWF_API int mjwf_mjs_delete(mjSpec * spec, mjsElement * element);
MJWF_API void mjwf_mjs_deleteUserValue(mjsElement * element, const char * key);
MJWF_API mjsBody * mjwf_mjs_findBody(mjSpec * s, const char * name);
MJWF_API mjsBody * mjwf_mjs_findChild(mjsBody * body, const char * name);
MJWF_API mjsDefault * mjwf_mjs_findDefault(mjSpec * s, const char * classname);
MJWF_API mjsElement * mjwf_mjs_findElement(mjSpec * s, mjtObj type, const char * name);
MJWF_API mjsFrame * mjwf_mjs_findFrame(mjSpec * s, const char * name);
MJWF_API mjSpec * mjwf_mjs_findSpec(mjSpec * spec, const char * name);
MJWF_API mjsElement * mjwf_mjs_firstChild(mjsBody * body, mjtObj type, int recurse);
MJWF_API mjsElement * mjwf_mjs_firstElement(mjSpec * s, mjtObj type);
MJWF_API mjsDefault * mjwf_mjs_getDefault(mjsElement * element);
MJWF_API const double * mjwf_mjs_getDouble(const mjDoubleVec * source, int * size);
MJWF_API const char * mjwf_mjs_getError(mjSpec * s);
MJWF_API mjsFrame * mjwf_mjs_getFrame(mjsElement * element);
MJWF_API int mjwf_mjs_getId(mjsElement * element);
MJWF_API mjString * mjwf_mjs_getName(mjsElement * element);
MJWF_API mjsBody * mjwf_mjs_getParent(mjsElement * element);
MJWF_API const void * mjwf_mjs_getPluginAttributes(const mjsPlugin * plugin);
MJWF_API mjSpec * mjwf_mjs_getSpec(mjsElement * element);
MJWF_API mjsDefault * mjwf_mjs_getSpecDefault(mjSpec * s);
MJWF_API const char * mjwf_mjs_getString(const mjString * source);
MJWF_API const void * mjwf_mjs_getUserValue(mjsElement * element, const char * key);
MJWF_API mjsWrap * mjwf_mjs_getWrap(const mjsTendon * tendonspec, int i);
MJWF_API double mjwf_mjs_getWrapCoef(mjsWrap * wrap);
MJWF_API double mjwf_mjs_getWrapDivisor(mjsWrap * wrap);
MJWF_API int mjwf_mjs_getWrapNum(const mjsTendon * tendonspec);
MJWF_API mjsSite * mjwf_mjs_getWrapSideSite(mjsWrap * wrap);
MJWF_API mjsElement * mjwf_mjs_getWrapTarget(mjsWrap * wrap);
MJWF_API int mjwf_mjs_isWarning(mjSpec * s);
MJWF_API int mjwf_mjs_makeMesh(mjsMesh * mesh, mjtMeshBuiltin builtin, double * params, int nparams);
MJWF_API mjsElement * mjwf_mjs_nextChild(mjsBody * body, mjsElement * child, int recurse);
MJWF_API mjsElement * mjwf_mjs_nextElement(mjSpec * s, mjsElement * element);
MJWF_API const char * mjwf_mjs_resolveOrientation(double quat[4], mjtByte degree, const char * sequence, const mjsOrientation * orientation);
MJWF_API int mjwf_mjs_sensorDim(const mjsSensor * sensor);
MJWF_API void mjwf_mjs_setBuffer(mjByteVec * dest, const void * array, int size);
MJWF_API int mjwf_mjs_setDeepCopy(mjSpec * s, int deepcopy);
MJWF_API void mjwf_mjs_setDefault(mjsElement * element, const mjsDefault * def);
MJWF_API void mjwf_mjs_setDouble(mjDoubleVec * dest, const double * array, int size);
MJWF_API void mjwf_mjs_setFloat(mjFloatVec * dest, const float * array, int size);
MJWF_API int mjwf_mjs_setFrame(mjsElement * dest, mjsFrame * frame);
MJWF_API mjtByte mjwf_mjs_setInStringVec(mjStringVec * dest, int i, const char * text);
MJWF_API void mjwf_mjs_setInt(mjIntVec * dest, const int * array, int size);
MJWF_API int mjwf_mjs_setName(mjsElement * element, const char * name);
MJWF_API void mjwf_mjs_setPluginAttributes(mjsPlugin * plugin, void * attributes);
MJWF_API void mjwf_mjs_setString(mjString * dest, const char * text);
MJWF_API void mjwf_mjs_setStringVec(mjStringVec * dest, const char * text);
MJWF_API const char * mjwf_mjs_setToAdhesion(mjsActuator * actuator, double gain);
MJWF_API const char * mjwf_mjs_setToCylinder(mjsActuator * actuator, double timeconst, double bias, double area, double diameter);
MJWF_API const char * mjwf_mjs_setToDamper(mjsActuator * actuator, double kv);
MJWF_API const char * mjwf_mjs_setToIntVelocity(mjsActuator * actuator, double kp, double kv[1], double dampratio[1], double timeconst[1], double inheritrange);
MJWF_API const char * mjwf_mjs_setToMotor(mjsActuator * actuator);
MJWF_API const char * mjwf_mjs_setToMuscle(mjsActuator * actuator, double timeconst[2], double tausmooth, double range[2], double force, double scale, double lmin, double lmax, double vmax, double fpmax, double fvmax);
MJWF_API const char * mjwf_mjs_setToPosition(mjsActuator * actuator, double kp, double kv[1], double dampratio[1], double timeconst[1], double inheritrange);
MJWF_API const char * mjwf_mjs_setToVelocity(mjsActuator * actuator, double kv);
MJWF_API void mjwf_mjs_setUserValue(mjsElement * element, const char * key, const void * data);
MJWF_API mjsWrap * mjwf_mjs_wrapGeom(mjsTendon * tendon, const char * name, const char * sidesite);
MJWF_API mjsWrap * mjwf_mjs_wrapJoint(mjsTendon * tendon, const char * name, double coef);
MJWF_API mjsWrap * mjwf_mjs_wrapPulley(mjsTendon * tendon, double divisor);
MJWF_API mjsWrap * mjwf_mjs_wrapSite(mjsTendon * tendon, const char * name);
MJWF_API mjtNum mjwf_mju_Halton(int index, int base);
MJWF_API mjtNum mjwf_mju_L1(const mjtNum * vec, int n);
MJWF_API void mjwf_mju_add(mjtNum * res, const mjtNum * vec1, const mjtNum * vec2, int n);
MJWF_API void mjwf_mju_add3(mjtNum res[3], const mjtNum vec1[3], const mjtNum vec2[3]);
MJWF_API void mjwf_mju_addScl(mjtNum * res, const mjtNum * vec1, const mjtNum * vec2, mjtNum scl, int n);
MJWF_API void mjwf_mju_addScl3(mjtNum res[3], const mjtNum vec1[3], const mjtNum vec2[3], mjtNum scl);
MJWF_API void mjwf_mju_addTo(mjtNum * res, const mjtNum * vec, int n);
MJWF_API void mjwf_mju_addTo3(mjtNum res[3], const mjtNum vec[3]);
MJWF_API void mjwf_mju_addToScl(mjtNum * res, const mjtNum * vec, mjtNum scl, int n);
MJWF_API void mjwf_mju_addToScl3(mjtNum res[3], const mjtNum vec[3], mjtNum scl);
MJWF_API void mjwf_mju_axisAngle2Quat(mjtNum res[4], const mjtNum axis[3], mjtNum angle);
MJWF_API void mjwf_mju_band2Dense(mjtNum * res, const mjtNum * mat, int ntotal, int nband, int ndense, mjtByte flg_sym);
MJWF_API int mjwf_mju_bandDiag(int i, int ntotal, int nband, int ndense);
MJWF_API void mjwf_mju_bandMulMatVec(mjtNum * res, const mjtNum * mat, const mjtNum * vec, int ntotal, int nband, int ndense, int nvec, mjtByte flg_sym);
MJWF_API void mjwf_mju_bindThreadPool(mjData * d, void * thread_pool);
MJWF_API int mjwf_mju_boxQP(mjtNum * res, mjtNum * R, int * index, const mjtNum * H, const mjtNum * g, int n, const mjtNum * lower, const mjtNum * upper);
MJWF_API void mjwf_mju_boxQPmalloc(mjtNum * * res, mjtNum * * R, int * * index, mjtNum * * H, mjtNum * * g, int n, mjtNum * * lower, mjtNum * * upper);
MJWF_API int mjwf_mju_cholFactor(mjtNum * mat, int n, mjtNum mindiag);
MJWF_API mjtNum mjwf_mju_cholFactorBand(mjtNum * mat, int ntotal, int nband, int ndense, mjtNum diagadd, mjtNum diagmul);
MJWF_API void mjwf_mju_cholSolve(mjtNum * res, const mjtNum * mat, const mjtNum * vec, int n);
MJWF_API void mjwf_mju_cholSolveBand(mjtNum * res, const mjtNum * mat, const mjtNum * vec, int ntotal, int nband, int ndense);
MJWF_API int mjwf_mju_cholUpdate(mjtNum * mat, mjtNum * x, int n, int flg_plus);
MJWF_API void mjwf_mju_clearHandlers(void);
MJWF_API mjtNum mjwf_mju_clip(mjtNum x, mjtNum min, mjtNum max);
MJWF_API void mjwf_mju_closeResource(mjResource * resource);
MJWF_API void mjwf_mju_copy(mjtNum * res, const mjtNum * vec, int n);
MJWF_API void mjwf_mju_copy3(mjtNum res[3], const mjtNum data[3]);
MJWF_API void mjwf_mju_copy4(mjtNum res[4], const mjtNum data[4]);
MJWF_API void mjwf_mju_cross(mjtNum res[3], const mjtNum a[3], const mjtNum b[3]);
MJWF_API void mjwf_mju_d2n(mjtNum * res, const double * vec, int n);
MJWF_API void mjwf_mju_decodePyramid(mjtNum * force, const mjtNum * pyramid, const mjtNum * mu, int dim);
MJWF_API mjSpec * mjwf_mju_decodeResource(mjResource * resource, const char * content_type, const mjVFS * vfs);
MJWF_API void mjwf_mju_defaultTask(mjTask * task);
MJWF_API void mjwf_mju_dense2Band(mjtNum * res, const mjtNum * mat, int ntotal, int nband, int ndense);
MJWF_API int mjwf_mju_dense2sparse(mjtNum * res, const mjtNum * mat, int nr, int nc, int * rownnz, int * rowadr, int * colind, int nnz);
MJWF_API void mjwf_mju_derivQuat(mjtNum res[4], const mjtNum quat[4], const mjtNum vel[3]);
MJWF_API mjtNum mjwf_mju_dist3(const mjtNum pos1[3], const mjtNum pos2[3]);
MJWF_API mjtNum mjwf_mju_dot(const mjtNum * vec1, const mjtNum * vec2, int n);
MJWF_API mjtNum mjwf_mju_dot3(const mjtNum vec1[3], const mjtNum vec2[3]);
MJWF_API int mjwf_mju_eig3(mjtNum eigval[3], mjtNum eigvec[9], mjtNum quat[4], const mjtNum mat[9]);
MJWF_API void mjwf_mju_encodePyramid(mjtNum * pyramid, const mjtNum * force, const mjtNum * mu, int dim);
MJWF_API void mjwf_mju_error(const char * msg);
MJWF_API void mjwf_mju_error_i(const char * msg, int i);
MJWF_API void mjwf_mju_error_s(const char * msg, const char * text);
MJWF_API void mjwf_mju_euler2Quat(mjtNum quat[4], const mjtNum euler[3], const char * seq);
MJWF_API void mjwf_mju_eye(mjtNum * mat, int n);
MJWF_API void mjwf_mju_f2n(mjtNum * res, const float * vec, int n);
MJWF_API void mjwf_mju_fill(mjtNum * res, mjtNum val, int n);
MJWF_API void mjwf_mju_free(void * ptr);
MJWF_API void mjwf_mju_getResourceDir(mjResource * resource, const char * * dir, int * ndir);
MJWF_API void mjwf_mju_getXMLDependencies(const char * filename, mjStringVec * dependencies);
MJWF_API void mjwf_mju_insertionSort(mjtNum * list, int n);
MJWF_API void mjwf_mju_insertionSortInt(int * list, int n);
MJWF_API int mjwf_mju_isBad(mjtNum x);
MJWF_API int mjwf_mju_isModifiedResource(const mjResource * resource, const char * timestamp);
MJWF_API int mjwf_mju_isZero(const mjtNum * vec, int n);
MJWF_API void * mjwf_mju_malloc(size_t size);
MJWF_API void mjwf_mju_mat2Quat(mjtNum quat[4], const mjtNum mat[9]);
MJWF_API int mjwf_mju_mat2Rot(mjtNum quat[4], const mjtNum mat[9]);
MJWF_API mjtNum mjwf_mju_max(mjtNum a, mjtNum b);
MJWF_API mjtNum mjwf_mju_min(mjtNum a, mjtNum b);
MJWF_API void mjwf_mju_mulMatMat(mjtNum * res, const mjtNum * mat1, const mjtNum * mat2, int r1, int c1, int c2);
MJWF_API void mjwf_mju_mulMatMatT(mjtNum * res, const mjtNum * mat1, const mjtNum * mat2, int r1, int c1, int r2);
MJWF_API void mjwf_mju_mulMatTMat(mjtNum * res, const mjtNum * mat1, const mjtNum * mat2, int r1, int c1, int c2);
MJWF_API void mjwf_mju_mulMatTVec(mjtNum * res, const mjtNum * mat, const mjtNum * vec, int nr, int nc);
MJWF_API void mjwf_mju_mulMatTVec3(mjtNum res[3], const mjtNum mat[9], const mjtNum vec[3]);
MJWF_API void mjwf_mju_mulMatVec(mjtNum * res, const mjtNum * mat, const mjtNum * vec, int nr, int nc);
MJWF_API void mjwf_mju_mulMatVec3(mjtNum res[3], const mjtNum mat[9], const mjtNum vec[3]);
MJWF_API void mjwf_mju_mulPose(mjtNum posres[3], mjtNum quatres[4], const mjtNum pos1[3], const mjtNum quat1[4], const mjtNum pos2[3], const mjtNum quat2[4]);
MJWF_API void mjwf_mju_mulQuat(mjtNum res[4], const mjtNum quat1[4], const mjtNum quat2[4]);
MJWF_API void mjwf_mju_mulQuatAxis(mjtNum res[4], const mjtNum quat[4], const mjtNum axis[3]);
MJWF_API mjtNum mjwf_mju_mulVecMatVec(const mjtNum * vec1, const mjtNum * mat, const mjtNum * vec2, int n);
MJWF_API mjtNum mjwf_mju_muscleBias(mjtNum len, const mjtNum lengthrange[2], mjtNum acc0, const mjtNum prm[9]);
MJWF_API mjtNum mjwf_mju_muscleDynamics(mjtNum ctrl, mjtNum act, const mjtNum prm[3]);
MJWF_API mjtNum mjwf_mju_muscleGain(mjtNum len, mjtNum vel, const mjtNum lengthrange[2], mjtNum acc0, const mjtNum prm[9]);
MJWF_API void mjwf_mju_n2d(double * res, const mjtNum * vec, int n);
MJWF_API void mjwf_mju_n2f(float * res, const mjtNum * vec, int n);
MJWF_API void mjwf_mju_negPose(mjtNum posres[3], mjtNum quatres[4], const mjtNum pos[3], const mjtNum quat[4]);
MJWF_API void mjwf_mju_negQuat(mjtNum res[4], const mjtNum quat[4]);
MJWF_API mjtNum mjwf_mju_norm(const mjtNum * res, int n);
MJWF_API mjtNum mjwf_mju_norm3(const mjtNum vec[3]);
MJWF_API mjtNum mjwf_mju_normalize(mjtNum * res, int n);
MJWF_API mjtNum mjwf_mju_normalize3(mjtNum vec[3]);
MJWF_API mjtNum mjwf_mju_normalize4(mjtNum vec[4]);
MJWF_API mjResource * mjwf_mju_openResource(const char * dir, const char * name, const mjVFS * vfs, char * error, size_t nerror);
MJWF_API void mjwf_mju_printMat(const mjtNum * mat, int nr, int nc);
MJWF_API void mjwf_mju_printMatSparse(const mjtNum * mat, int nr, const int * rownnz, const int * rowadr, const int * colind);
MJWF_API void mjwf_mju_quat2Mat(mjtNum res[9], const mjtNum quat[4]);
MJWF_API void mjwf_mju_quat2Vel(mjtNum res[3], const mjtNum quat[4], mjtNum dt);
MJWF_API void mjwf_mju_quatIntegrate(mjtNum quat[4], const mjtNum vel[3], mjtNum scale);
MJWF_API void mjwf_mju_quatZ2Vec(mjtNum quat[4], const mjtNum vec[3]);
MJWF_API mjtNum mjwf_mju_rayGeom(const mjtNum pos[3], const mjtNum mat[9], const mjtNum size[3], const mjtNum pnt[3], const mjtNum vec[3], int geomtype, mjtNum normal[3]);
MJWF_API mjtNum mjwf_mju_raySkin(int nface, int nvert, const int * face, const float * vert, const mjtNum pnt[3], const mjtNum vec[3], int vertid[1]);
MJWF_API int mjwf_mju_readResource(mjResource * resource, const void * * buffer);
MJWF_API void mjwf_mju_rotVecQuat(mjtNum res[3], const mjtNum vec[3], const mjtNum quat[4]);
MJWF_API int mjwf_mju_round(mjtNum x);
MJWF_API void mjwf_mju_scl(mjtNum * res, const mjtNum * vec, mjtNum scl, int n);
MJWF_API void mjwf_mju_scl3(mjtNum res[3], const mjtNum vec[3], mjtNum scl);
MJWF_API mjtNum mjwf_mju_sigmoid(mjtNum x);
MJWF_API mjtNum mjwf_mju_sign(mjtNum x);
MJWF_API void mjwf_mju_sparse2dense(mjtNum * res, const mjtNum * mat, int nr, int nc, const int * rownnz, const int * rowadr, const int * colind);
MJWF_API mjtNum mjwf_mju_springDamper(mjtNum pos0, mjtNum vel0, mjtNum Kp, mjtNum Kv, mjtNum dt);
MJWF_API void mjwf_mju_sqrMatTD(mjtNum * res, const mjtNum * mat, const mjtNum * diag, int nr, int nc);
MJWF_API mjtNum mjwf_mju_standardNormal(mjtNum * num2);
MJWF_API int mjwf_mju_str2Type(const char * str);
MJWF_API char * mjwf_mju_strncpy(char * dst, const char * src, int n);
MJWF_API void mjwf_mju_sub(mjtNum * res, const mjtNum * vec1, const mjtNum * vec2, int n);
MJWF_API void mjwf_mju_sub3(mjtNum res[3], const mjtNum vec1[3], const mjtNum vec2[3]);
MJWF_API void mjwf_mju_subFrom(mjtNum * res, const mjtNum * vec, int n);
MJWF_API void mjwf_mju_subFrom3(mjtNum res[3], const mjtNum vec[3]);
MJWF_API void mjwf_mju_subQuat(mjtNum res[3], const mjtNum qa[4], const mjtNum qb[4]);
MJWF_API mjtNum mjwf_mju_sum(const mjtNum * vec, int n);
MJWF_API void mjwf_mju_symmetrize(mjtNum * res, const mjtNum * mat, int n);
MJWF_API void mjwf_mju_taskJoin(mjTask * task);
MJWF_API mjThreadPool * mjwf_mju_threadPoolCreate(size_t number_of_threads);
MJWF_API void mjwf_mju_threadPoolDestroy(mjThreadPool * thread_pool);
MJWF_API void mjwf_mju_threadPoolEnqueue(mjThreadPool * thread_pool, mjTask * task);
MJWF_API void mjwf_mju_transformSpatial(mjtNum res[6], const mjtNum vec[6], int flg_force, const mjtNum newpos[3], const mjtNum oldpos[3], const mjtNum rotnew2old[9]);
MJWF_API void mjwf_mju_transpose(mjtNum * res, const mjtNum * mat, int nr, int nc);
MJWF_API void mjwf_mju_trnVecPose(mjtNum res[3], const mjtNum pos[3], const mjtNum quat[4], const mjtNum vec[3]);
MJWF_API const char * mjwf_mju_type2Str(int type);
MJWF_API void mjwf_mju_unit4(mjtNum res[4]);
MJWF_API void mjwf_mju_warning(const char * msg);
MJWF_API const char * mjwf_mju_warningText(int warning, size_t info);
MJWF_API void mjwf_mju_warning_i(const char * msg, int i);
MJWF_API void mjwf_mju_warning_s(const char * msg, const char * text);
MJWF_API void mjwf_mju_writeLog(const char * type, const char * msg);
MJWF_API const char * mjwf_mju_writeNumBytes(size_t nbytes);
MJWF_API void mjwf_mju_zero(mjtNum * res, int n);
MJWF_API void mjwf_mju_zero3(mjtNum res[3]);
MJWF_API void mjwf_mju_zero4(mjtNum res[4]);
MJWF_API void mjwf_mjv_addGeoms(const mjModel * m, mjData * d, const mjvOption * opt, const mjvPerturb * pert, int catmask, mjvScene * scn);
MJWF_API void mjwf_mjv_alignToCamera(mjtNum res[3], const mjtNum vec[3], const mjtNum forward[3]);
MJWF_API void mjwf_mjv_applyPerturbForce(const mjModel * m, mjData * d, const mjvPerturb * pert);
MJWF_API void mjwf_mjv_applyPerturbPose(const mjModel * m, mjData * d, const mjvPerturb * pert, int flg_paused);
MJWF_API mjvGLCamera mjwf_mjv_averageCamera(const mjvGLCamera * cam1, const mjvGLCamera * cam2);
MJWF_API void mjwf_mjv_cameraFrame(mjtNum headpos[3], mjtNum forward[3], mjtNum up[3], mjtNum right[3], const mjData * d, const mjvCamera * cam);
MJWF_API void mjwf_mjv_cameraFrustum(float zver[2], float zhor[2], float zclip[2], const mjModel * m, const mjvCamera * cam);
MJWF_API void mjwf_mjv_cameraInModel(mjtNum headpos[3], mjtNum forward[3], mjtNum up[3], const mjvScene * scn);
MJWF_API void mjwf_mjv_cameraInRoom(mjtNum headpos[3], mjtNum forward[3], mjtNum up[3], const mjvScene * scn);
MJWF_API void mjwf_mjv_connector(mjvGeom * geom, int type, mjtNum width, const mjtNum from[3], const mjtNum to[3]);
MJWF_API mjData * mjwf_mjv_copyData(mjData * dest, const mjModel * m, const mjData * src);
MJWF_API void mjwf_mjv_copyModel(mjModel * dest, const mjModel * src);
MJWF_API void mjwf_mjv_defaultCamera(mjvCamera * cam);
MJWF_API void mjwf_mjv_defaultFigure(mjvFigure * fig);
MJWF_API void mjwf_mjv_defaultFreeCamera(const mjModel * m, mjvCamera * cam);
MJWF_API void mjwf_mjv_defaultOption(mjvOption * opt);
MJWF_API void mjwf_mjv_defaultPerturb(mjvPerturb * pert);
MJWF_API void mjwf_mjv_defaultScene(mjvScene * scn);
MJWF_API void mjwf_mjv_freeScene(mjvScene * scn);
MJWF_API mjtNum mjwf_mjv_frustumHeight(const mjvScene * scn);
MJWF_API void mjwf_mjv_initGeom(mjvGeom * geom, int type, const mjtNum size[3], const mjtNum pos[3], const mjtNum mat[9], const float rgba[4]);
MJWF_API void mjwf_mjv_initPerturb(const mjModel * m, mjData * d, const mjvScene * scn, mjvPerturb * pert);
MJWF_API void mjwf_mjv_makeLights(const mjModel * m, const mjData * d, mjvScene * scn);
MJWF_API void mjwf_mjv_makeScene(const mjModel * m, mjvScene * scn, int maxgeom);
MJWF_API void mjwf_mjv_model2room(mjtNum roompos[3], mjtNum roomquat[4], const mjtNum modelpos[3], const mjtNum modelquat[4], const mjvScene * scn);
MJWF_API void mjwf_mjv_moveCamera(const mjModel * m, int action, mjtNum reldx, mjtNum reldy, const mjvScene * scn, mjvCamera * cam);
MJWF_API void mjwf_mjv_moveModel(const mjModel * m, int action, mjtNum reldx, mjtNum reldy, const mjtNum roomup[3], mjvScene * scn);
MJWF_API void mjwf_mjv_movePerturb(const mjModel * m, const mjData * d, int action, mjtNum reldx, mjtNum reldy, const mjvScene * scn, mjvPerturb * pert);
MJWF_API void mjwf_mjv_room2model(mjtNum modelpos[3], mjtNum modelquat[4], const mjtNum roompos[3], const mjtNum roomquat[4], const mjvScene * scn);
MJWF_API int mjwf_mjv_select(const mjModel * m, const mjData * d, const mjvOption * vopt, mjtNum aspectratio, mjtNum relx, mjtNum rely, const mjvScene * scn, mjtNum selpnt[3], int geomid[1], int flexid[1], int skinid[1]);
MJWF_API void mjwf_mjv_updateCamera(const mjModel * m, const mjData * d, mjvCamera * cam, mjvScene * scn);
MJWF_API void mjwf_mjv_updateScene(const mjModel * m, mjData * d, const mjvOption * opt, const mjvPerturb * pert, mjvCamera * cam, int catmask, mjvScene * scn);
MJWF_API void mjwf_mjv_updateSkin(const mjModel * m, const mjData * d, mjvScene * scn);

#undef MJWF_API

#ifdef __cplusplus
}  // extern "C"
#endif
