#!/usr/bin/env python3
"""
Generate mjwf_* function wrappers and export manifests from the current
in dist/<ver>/abi tree.

Special handling (kept explicit and minimal):
  - Prefix whitelist:
      We only wrap MuJoCo C API functions whose names start with:
        mj_  /  mju_  /  mjs_  /  mjd_  /  mjv_
      This includes MuJoCo's visualization scene generation entrypoints
      (mjv_updateScene etc.) while still excluding renderer/UI/thread helper
      prefixes such as mjr_ / mjui_ / mjthread_. The goal is to keep the
      exported surface introspect-driven and avoid exporting incidental helpers.
  - Variadic functions:
      The official introspect FUNCTION table normalises varargs: functions
      like mju_error / mju_warning are represented as fixed-signature
      declarations, and their _i / _s variants are listed explicitly.
      We therefore treat all functions as non-variadic and do not generate
      any special *_v adapters; the C headers remain the single source of
      truth for the true printf-like semantics.
  - Runtime helpers:
      Low-level Emscripten runtime helpers (_malloc/_free/_realloc) are not
      wrapped as mjwf_* functions. Instead they are listed separately in the
      manifest's runtime_keep set so that the JS side can still call them.

Inputs (defaults from dist/<ver>/abi):
  - functions_introspect_like.json
      A-set: MuJoCo C API declarations from official introspect (JSON view with C declarators).
  - nm_symbols.json
      B-set: implemented symbols in libmujoco.a as reported by llvm-nm.
  - app/mjwf_abi_structs.lst
      Additional plain exports (struct pointers etc.) generated by gen_structs.

Outputs (when run with defaults from the repo root):
  - app/mjwf_abi_funcs.h
  - app/mjwf_abi_funcs.c
  - wrapper_exports_funcs.json (under dist/<ver>/abi)
      Export manifest for functions-only (struct exports are tracked separately
      via mjwf_extra_exports.lst and gen_structs.py).
  - exports_report_funcs.md (under dist/<ver>/abi)
      A/B/C overview for functions. If a baseline manifest is provided,
      the report also includes a small diff section.

This script is intentionally self-contained and introspect-driven so that
the function export pipeline does not depend on header re-parsing or
Node-based codegen.
"""


from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Set, Tuple

from dist_version import abi_dir as resolve_abi_dir, dist_version as detect_dist_version


ALLOWED_PREFIXES: Tuple[str, ...] = ("mj_", "mju_", "mjs_", "mjd_", "mjv_")
RUNTIME_KEEP: Tuple[str, ...] = ("_malloc", "_free", "_realloc")


@dataclass
class FunctionDecl:
    """Minimal view of a function from functions_introspect_like.json."""

    name: str
    return_type: str
    param_decls: List[str]
    param_names: List[str]


def _repo_root() -> Path:
    # .../abi_exports -> repo root at parents[1]
    return Path(__file__).resolve().parents[1]


def load_functions_from_introspect(
    path: Path,
) -> Tuple[Dict[str, FunctionDecl], Set[str], dict]:
    """Load A-set declarations from functions_introspect_like.json.

    The JSON is produced by introspect/forge/scan_clang_introspect.py and
    already contains declarator strings computed via the official AST
    printer (return_decl / param_decls).
    """
    payload = json.loads(path.read_text(encoding="utf-8"))
    fn_map: Dict[str, FunctionDecl] = {}
    functions = payload.get("functions", []) or []
    for entry in functions:
        name = entry.get("name")
        if not name:
            continue
        return_type = str(entry.get("return_decl") or "void")
        param_decls = [str(p) for p in entry.get("param_decls", []) or []]
        param_names = [str(p) for p in entry.get("param_names", []) or []]
        fn_map[name] = FunctionDecl(
            name=name,
            return_type=return_type,
            param_decls=param_decls,
            param_names=param_names,
        )

    names = {str(entry.get("name")) for entry in functions if entry.get("name")}
    return fn_map, names, payload


def load_nm_symbols(path: Path) -> Set[str]:
    """Load B-set implemented symbol names from nm_symbols.json."""
    payload = json.loads(path.read_text(encoding="utf-8"))
    symbols = payload.get("symbols") or []
    return set(str(s) for s in symbols)


def load_extra_names(path: Optional[Path]) -> List[str]:
    if path is None or not path.is_file():
        return []
    out: List[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        out.append(line)
    return out


def is_allowed_prefix(name: str) -> bool:
    return name.startswith(ALLOWED_PREFIXES)


def generate_header(funcs: Sequence[FunctionDecl]) -> str:
    lines: List[str] = []
    lines.append("// AUTO-GENERATED: MuJoCo WASM function wrapper declarations.")
    lines.append("// Source: abi_exports/gen_funcs.py")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <mujoco/mujoco.h>")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")
    lines.append("#if defined(__EMSCRIPTEN__)")
    lines.append("#  include <emscripten/emscripten.h>")
    lines.append(
        '#  define MJWF_API EMSCRIPTEN_KEEPALIVE '
        '__attribute__((used, visibility("default")))'
    )
    lines.append("#else")
    lines.append('#  define MJWF_API __attribute__((used, visibility("default")))')
    lines.append("#endif")
    lines.append("")

    for fn in funcs:
        params = fn.param_decls or []
        param_list = ", ".join(params) if params else "void"
        lines.append(f"MJWF_API {fn.return_type} mjwf_{fn.name}({param_list});")

    lines.append("")
    lines.append("#undef MJWF_API")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append("}  // extern \"C\"")
    lines.append("#endif")
    lines.append("")
    return "\n".join(lines)


def generate_source(funcs: Sequence[FunctionDecl]) -> str:
    lines: List[str] = []
    lines.append("// AUTO-GENERATED: MuJoCo WASM function wrapper implementations.")
    lines.append("// Source: abi_exports/gen_funcs.py")
    lines.append('#include "mjwf_abi_funcs.h"')
    lines.append("")
    lines.append("#if defined(__EMSCRIPTEN__)")
    lines.append("#  include <emscripten/emscripten.h>")
    lines.append(
        '#  define MJWF_API_IMPL EMSCRIPTEN_KEEPALIVE '
        '__attribute__((used, visibility("default")))'
    )
    lines.append("#else")
    lines.append(
        '#  define MJWF_API_IMPL __attribute__((used, visibility("default")))'
    )
    lines.append("#endif")
    lines.append("")

    for fn in funcs:
        params = fn.param_decls or []
        names = fn.param_names or []
        param_list = ", ".join(params) if params else "void"
        call_args = ", ".join(names) if names else ""
        call_expr = f"{fn.name}({call_args})" if call_args else f"{fn.name}()"
        ret_type = fn.return_type.strip() or "void"
        ret_kw = "" if ret_type == "void" else "return "

        lines.append(
            f"MJWF_API_IMPL {fn.return_type} mjwf_{fn.name}({param_list}) {{"
        )
        lines.append(f"  {ret_kw}{call_expr};")
        lines.append("}")
        lines.append("")

    lines.append("#undef MJWF_API_IMPL")
    lines.append("")
    return "\n".join(lines)


def build_manifest(
    version: str, function_names: Sequence[str], extra_names: Sequence[str]
) -> dict:
    all_names_sorted = sorted(set(function_names) | set(extra_names))
    generated_at = datetime.now(timezone.utc).isoformat()
    return {
        "generatedAt": generated_at,
        "version": version,
        "count": len(all_names_sorted),
        "names": all_names_sorted,
        "required": [f"_mjwf_{n}" for n in all_names_sorted],
        "optional": [],
        "runtime_keep": list(RUNTIME_KEEP),
    }


def diff_against_baseline(
    current_names: Iterable[str], baseline_path: Optional[Path]
) -> Tuple[List[str], List[str]]:
    if baseline_path is None or not baseline_path.is_file():
        return ([], [])
    baseline_payload = json.loads(baseline_path.read_text(encoding="utf-8"))
    baseline_names = set(baseline_payload.get("names") or [])
    current_set = set(current_names)
    baseline_only = sorted(baseline_names - current_set)
    current_only = sorted(current_set - baseline_names)
    return baseline_only, current_only


def format_report(
    version: str,
    count_a: int,
    count_b: int,
    func_names: Sequence[str],
    special_exclusions: Sequence[Tuple[str, str]],
    a_minus_b: Sequence[str],
    b_minus_a: Sequence[str],
    ab_minus_c: Sequence[str],
    baseline_only: Sequence[str],
    current_only: Sequence[str],
) -> str:
    """Emit a concise A/B/C report for functions, plus baseline diff."""
    count_mj = sum(1 for n in func_names if n.startswith("mj_"))
    count_mju = sum(1 for n in func_names if n.startswith("mju_"))
    count_mjs = sum(1 for n in func_names if n.startswith("mjs_"))
    count_mjd = sum(1 for n in func_names if n.startswith("mjd_"))

    def _slice(lines: Sequence[str], limit: int = 50) -> List[str]:
        if not lines:
            return ["- none"]
        if len(lines) <= limit:
            return [f"- {x}" for x in lines]
        head = [f"- {x}" for x in lines[:limit]]
        head.append(f"- ... (+{len(lines) - limit} more)")
        return head

    lines: List[str] = []
    lines.append(f"# MuJoCo WASM Function Export Report (ver {version})")
    lines.append("")
    lines.append("## Special Rules")
    lines.append(
        "- Prefix whitelist: export only `mj_`, `mju_`, `mjs_`, `mjd_` symbols; "
        "rendering/UI/thread helpers (mjv_/mjr_/mjui_/mjthread_) are excluded."
    )
    lines.append(
        "- Variadic: introspect treats varargs functions as fixed signatures, "
        "so gen_funcs.py does not synthesise *_v adapters; mju_error/mju_warning "
        "are exported with their introspect-declared parameter lists."
    )
    lines.append(
        "- Runtime helpers: `_malloc`, `_free`, `_realloc` are kept via "
        "runtime_keep and not wrapped as mjwf_*."
    )
    lines.append("")
    lines.append("## A, B, C Overview")
    lines.append(
        "- A: declarations from dist/<ver>/abi/functions_introspect_like.json (introspect)."
    )
    lines.append(
        "- B: implemented symbols from dist/<ver>/abi/nm_symbols.json "
        "(llvm-nm -g --defined-only)."
    )
    lines.append(
        "- C: A ∩ B after applying prefix whitelist and any future exclusions, "
        "emitted as mjwf_* wrappers."
    )
    lines.append("- Hard gate: (A ∩ B) - C must be empty.")
    lines.append("")
    lines.append("## Totals")
    lines.append(f"- A: {count_a}")
    lines.append(f"- B: {count_b}")
    lines.append(f"- C (functions only): {len(func_names)}")
    lines.append(
        f"- Prefix breakdown: mj={count_mj}, mju={count_mju}, "
        f"mjs={count_mjs}, mjd={count_mjd}"
    )
    lines.append("")
    lines.append("## Special Exclusions (by name → reason)")
    if not special_exclusions:
        lines.append("- none")
    else:
        for name, reason in special_exclusions:
            lines.append(f"- {name} -> {reason}")
    lines.append("")
    lines.append("## Set Differences (for auditing)")
    lines.append(f"- A - B (declared only): {len(a_minus_b)}")
    lines.extend(_slice(a_minus_b))
    lines.append(f"- B - A (implemented only): {len(b_minus_a)}")
    lines.extend(_slice(b_minus_a))
    lines.append(f"- (A ∩ B) - C (should be zero): {len(ab_minus_c)}")
    lines.extend(_slice(ab_minus_c))
    lines.append("")
    lines.append("## Baseline Comparison (wrapper_exports.json)")
    lines.append(
        "- Baseline-only (present in snapshot, missing now): "
        f"{len(baseline_only)}"
    )
    lines.extend(_slice(list(baseline_only)))
    lines.append(
        "- Current-only (new in this run vs baseline): "
        f"{len(current_only)}"
    )
    lines.extend(_slice(list(current_only)))
    lines.append("")
    return "\n".join(lines)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--functions-json",
        type=Path,
        help="Path to functions_introspect_like.json (A-set declarations).",
    )
    parser.add_argument(
        "--nm",
        type=Path,
        help="Path to nm_symbols.json (B-set implementations).",
    )
    parser.add_argument(
        "--extra",
        type=Path,
        help="Optional extra exports list (e.g. struct ptr names).",
    )
    parser.add_argument(
        "--abi",
        type=Path,
        help="Optional path to dist/<ver>/abi directory.",
    )
    parser.add_argument(
        "--out-header",
        type=Path,
        help="Output path for mjwf_abi_funcs.h.",
    )
    parser.add_argument(
        "--out-source",
        type=Path,
        help="Output path for mjwf_abi_funcs.c.",
    )
    parser.add_argument(
        "--out-manifest",
        type=Path,
        help="Output path for wrapper_exports_funcs.json.",
    )
    parser.add_argument(
        "--out-report",
        type=Path,
        help="Output path for exports_report_funcs.md.",
    )
    parser.add_argument(
        "--out-exports",
        type=Path,
        help="Output path for exports.lst (Emscripten exported symbols list).",
    )
    parser.add_argument(
        "--version",
        default=None,
        help="MuJoCo version string used in reports (defaults to the dist/<ver> directory in repo).",
    )
    parser.add_argument(
        "--baseline",
        type=Path,
        help="Optional baseline wrapper_exports.json for comparison.",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)

    repo_root = _repo_root()
    target_version = detect_dist_version()
    version_label = args.version or target_version
    abi_dir = args.abi or resolve_abi_dir(target_version)

    functions_json_path = args.functions_json or (
        abi_dir / "functions_introspect_like.json"
    )
    nm_path = args.nm or (abi_dir / "nm_symbols.json")
    extra_path = args.extra or (repo_root / "app" / "mjwf_abi_structs.lst")
    out_header = args.out_header or (repo_root / "app" / "mjwf_abi_funcs.h")
    out_source = args.out_source or (repo_root / "app" / "mjwf_abi_funcs.c")
    out_manifest = args.out_manifest or (abi_dir / "wrapper_exports_funcs.json")
    out_report = args.out_report or (abi_dir / "exports_report_funcs.md")
    out_exports = args.out_exports or (abi_dir / "exports.lst")

    baseline_path = args.baseline

    if not functions_json_path.is_file():
        raise SystemExit(
            f"functions_introspect_like.json not found at {functions_json_path}"
        )
    if not nm_path.is_file():
        raise SystemExit(f"nm_symbols.json not found at {nm_path}")

    fn_map, names_a, _functions_payload = load_functions_from_introspect(
        functions_json_path
    )
    names_b = load_nm_symbols(nm_path)
    extra_names = load_extra_names(extra_path)

    intersection = sorted(names_a & names_b)

    special_exclusions: List[Tuple[str, str]] = []
    final_funcs: List[FunctionDecl] = []
    for name in intersection:
        fn = fn_map.get(name)
        if fn is None:
            continue
        if not is_allowed_prefix(name):
            special_exclusions.append((name, "non_core_prefix"))
            continue
        final_funcs.append(fn)

    final_func_names = [fn.name for fn in final_funcs]

    # Sanity sets for the A/B/C report.
    excluded_names = {name for (name, _reason) in special_exclusions}
    a_minus_b = sorted(names_a - names_b)
    b_minus_a = sorted(names_b - names_a)
    ab_names = set(intersection)
    c_names = set(final_func_names)
    ab_minus_c = sorted(
        name for name in ab_names if name not in excluded_names and name not in c_names
    )

    manifest = build_manifest(version_label, final_func_names, extra_names)

    # Compare against baseline wrapper_exports.json, if provided.
    baseline_only: List[str] = []
    current_only: List[str] = []
    if baseline_path is not None:
        baseline_only, current_only = diff_against_baseline(
            manifest.get("names", []), baseline_path
        )
    report_md = format_report(
        version=version_label,
        count_a=len(names_a),
        count_b=len(names_b),
        func_names=final_func_names,
        special_exclusions=special_exclusions,
        a_minus_b=a_minus_b,
        b_minus_a=b_minus_a,
        ab_minus_c=ab_minus_c,
        baseline_only=baseline_only,
        current_only=current_only,
    )

    # Emit header/source and manifest/report.
    out_header.parent.mkdir(parents=True, exist_ok=True)
    out_source.parent.mkdir(parents=True, exist_ok=True)
    abi_dir.mkdir(parents=True, exist_ok=True)

    out_header.write_text(generate_header(final_funcs), encoding="utf-8")
    out_source.write_text(generate_source(final_funcs), encoding="utf-8")
    out_manifest.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    out_report.write_text(report_md, encoding="utf-8")

    exports_list: List[str] = []
    exports_list.extend(manifest.get("required", []) or [])
    for name in manifest.get("runtime_keep", []) or []:
        if name not in exports_list:
            exports_list.append(name)
    out_exports.write_text(json.dumps(exports_list), encoding="utf-8")

    print(
    f"[gen-funcs] ver={version_label} A={len(names_a)} B={len(names_b)} "
        f"C={len(final_func_names)} extras={len(extra_names)}"
    )
    if baseline_only or current_only:
        print(
            f"[gen-funcs] baseline_only={len(baseline_only)} "
            f"current_only={len(current_only)}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
