name: forge-325

on:
  workflow_dispatch:
    inputs:
      publish:
        description: "Create GitHub Release after build"
        required: false
        default: 'false'
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Emscripten SDK (3.1.55)
        uses: mymindstorm/setup-emsdk@v13
        with:
          version: 3.1.55
          actions-cache-folder: emsdk-cache

      - name: Prepare MuJoCo 3.2.5 sources
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p external
          (git clone --depth 1 --branch 3.2.5 https://github.com/google-deepmind/mujoco external/mujoco) || {
            rm -rf external/mujoco || true
            git clone --depth 1 --branch v3.2.5 https://github.com/google-deepmind/mujoco external/mujoco
          }

      - name: Configure (WASM)
        shell: bash
        run: |
          emcmake cmake -S wrappers/official_app_325 -B build/325 \
            -DCMAKE_BUILD_TYPE=Release \
            -DMUJOCO_BUILD_EXAMPLES=OFF -DMUJOCO_BUILD_SIMULATE=OFF -DMUJOCO_BUILD_TESTS=OFF -DMUJOCO_BUILD_SAMPLES=OFF

      - name: Build
        shell: bash
        run: cmake --build build/325 -j 2

      - name: Configure (Native)
        shell: bash
        run: |
          cmake -S wrappers/official_app_325 -B build/325_native \
            -DCMAKE_BUILD_TYPE=Release \
            -DMUJOCO_BUILD_EXAMPLES=OFF -DMUJOCO_BUILD_SIMULATE=OFF -DMUJOCO_BUILD_TESTS=OFF -DMUJOCO_BUILD_SAMPLES=OFF

      - name: Build (Native)
        shell: bash
        run: cmake --build build/325_native -j 2

      - name: Collect artifacts
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p dist
          cp build/325/_wasm/mujoco_wasm325.js dist/mujoco-3.2.5.js
          cp build/325/_wasm/mujoco_wasm325.wasm dist/mujoco-3.2.5.wasm
          if [ -f build/325/_wasm/mujoco_wasm325.wasm.map ]; then cp build/325/_wasm/mujoco_wasm325.wasm.map dist/mujoco-3.2.5.wasm.map; fi
      - name: Run smoke test (Node)
        shell: bash
        run: node tests/smoke-325.mjs

      - name: Run regression test (WASM vs Native)
        shell: bash
        env:
          MJ_NATIVE_BIN: ${{ github.workspace }}/build/325_native/mujoco_compare325
        run: node tests/regression-325.mjs


      - name: Generate version.json
        shell: bash
        run: |
          set -euxo pipefail
          EMVER=3.1.55
          MJVER=3.2.5
          MJ_SHA=$(git -C external/mujoco rev-parse HEAD)
          JS=dist/mujoco-${MJVER}.js; WASM=dist/mujoco-${MJVER}.wasm
          JSB=$(stat -c %s "$JS") || JSB=0
          WSB=$(stat -c %s "$WASM") || WSB=0
          JSUM=$(sha256sum "$JS" | cut -d' ' -f1)
          WSUM=$(sha256sum "$WASM" | cut -d' ' -f1)
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          cat > dist/version.json <<JSON
          {
            "mujocoVersion": "${MJVER}",
            "emscripten": "${EMVER}",
            "buildTime": "${NOW}",
            "gitSha": "${MJ_SHA}",
            "features": {"qhulloff": true, "render": false, "plugins": false, "libccd": "static"},
            "size": {"wasmBytes": ${WSB}, "jsBytes": ${JSB}},
            "hash": {"wasmSha256": "${WSUM}", "jsSha256": "${JSUM}"}
          }
          JSON

      - name: Generate SBOM (SPDX json)
        shell: bash
        run: |
          set -euxo pipefail
          EMVER=3.1.55
          MJVER=3.2.5
          MJ_SHA=$(git -C external/mujoco rev-parse HEAD)
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          NS="https://github.com/lshdlut/mujoco-wasm-forge/sbom/${GITHUB_RUN_ID}"
          cat > dist/sbom.spdx.json <<SBOM
          {
            "spdxVersion": "SPDX-2.3",
            "dataLicense": "CC0-1.0",
            "SPDXID": "SPDXRef-DOCUMENT",
            "name": "mujoco-wasm-forge-${MJVER}",
            "documentNamespace": "${NS}",
            "creationInfo": {"created": "${NOW}", "creators": ["Tool: forge-325 workflow"]},
            "packages": [
              {"name": "mujoco", "SPDXID": "SPDXRef-Pkg-MuJoCo", "versionInfo": "${MJVER}", "downloadLocation": "https://github.com/google-deepmind/mujoco", "sourceInfo": "git@${MJ_SHA}"},
              {"name": "emscripten", "SPDXID": "SPDXRef-Pkg-Emscripten", "versionInfo": "${EMVER}", "downloadLocation": "https://github.com/emscripten-core/emsdk"}
            ]
          }
          SBOM

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mujoco-3.2.5
          path: dist/

      - name: Quality gates (size + init time)
        shell: bash
        env:
          QUALITY_ENFORCE: '0'
          WASM_MAX_BYTES: '16000000'
          JS_MAX_BYTES: '2000000'
          MAX_INIT_MS: '8000'
        run: node tests/gates-325.mjs

      - name: Create Release (optional)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.publish == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: mujoco-3.2.5-wasm
          name: Mujoco 3.2.5 WASM
          draft: false
          prerelease: false
          files: |
            dist/mujoco-3.2.5.js
            dist/mujoco-3.2.5.wasm
            dist/mujoco-3.2.5.wasm.map
            dist/version.json



