name: forge-337

on:
  workflow_dispatch:
    inputs:
      publish:
        description: "Create GitHub Release after build"
        required: false
        default: 'false'
  push:
    branches: [ main, master ]
    tags:
      - forge-3.3.7-*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Emscripten SDK (3.1.55)
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.55
          cache: false

      - name: Prepare MuJoCo 3.3.7 sources
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p external
          (git clone --depth 1 --branch v3.3.7 https://github.com/google-deepmind/mujoco external/mujoco) || true

      - name: Patch MuJoCo for Emscripten localtime_r
        shell: bash
        run: |
          set -euxo pipefail
          f=external/mujoco/src/engine/engine_util_errmem.c
          if [ -f "$f" ]; then
            sed -i "s/#if defined(_POSIX_C_SOURCE) || defined(__APPLE__) || defined(__STDC_VERSION_TIME_H__)/#if defined(_POSIX_C_SOURCE) || defined(__APPLE__) || defined(__EMSCRIPTEN__) || defined(__STDC_VERSION_TIME_H__)/" "$f"
            sed -i "s/#if defined(_POSIX_C_SOURCE) || defined(__APPLE__)/#if defined(_POSIX_C_SOURCE) || defined(__APPLE__) || defined(__EMSCRIPTEN__)/" "$f"
          fi

      - name: Configure (WASM)
        shell: bash
        run: |
          emcmake cmake -S wrappers/official_app_337 -B build/337 \
            -DCMAKE_BUILD_TYPE=Release \
            -DMUJOCO_BUILD_EXAMPLES=OFF -DMUJOCO_BUILD_SIMULATE=OFF -DMUJOCO_BUILD_TESTS=OFF -DMUJOCO_BUILD_SAMPLES=OFF \
            -DCMAKE_SKIP_INSTALL_RULES=ON \
            -DLIBM_LIBRARY:STRING=-lm

      - name: Build (WASM)
        shell: bash
        run: cmake --build build/337 -j 2

      - name: Configure (Native)
        shell: bash
        run: |
          cmake -S wrappers/official_app_337 -B build/337_native \
            -DCMAKE_BUILD_TYPE=Release \
            -DMUJOCO_BUILD_EXAMPLES=OFF -DMUJOCO_BUILD_SIMULATE=OFF -DMUJOCO_BUILD_TESTS=OFF -DMUJOCO_BUILD_SAMPLES=OFF \
            -DCMAKE_SKIP_INSTALL_RULES=ON

      - name: Build (Native)
        shell: bash
        run: cmake --build build/337_native -j 2

      - name: Collect artifacts
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p dist
          cp build/337/_wasm/mujoco_wasm337.js dist/mujoco-3.3.7.js
          cp build/337/_wasm/mujoco_wasm337.wasm dist/mujoco-3.3.7.wasm
          if [ -f build/337/_wasm/mujoco_wasm337.wasm.map ]; then cp build/337/_wasm/mujoco_wasm337.wasm.map dist/mujoco-3.3.7.wasm.map; fi

      - name: Run smoke test (Node)
        shell: bash
        run: node tests/smoke-337.mjs

      - name: Run regression test (WASM vs Native)
        shell: bash
        env:
          MJ_NATIVE_BIN: ${{ github.workspace }}/build/337_native/_wasm/mujoco_compare337
        run: node tests/regression-337.mjs

      - name: Generate version.json
        shell: bash
        run: |
          set -euxo pipefail
          EMVER=3.1.55
          MJVER=3.3.7
          MJ_SHA=$(git -C external/mujoco rev-parse HEAD)
          JS=dist/mujoco-${MJVER}.js; WASM=dist/mujoco-${MJVER}.wasm
          JSB=$(stat -c %s "$JS") || JSB=0
          WSB=$(stat -c %s "$WASM") || WSB=0
          JSUM=$(sha256sum "$JS" | cut -d' ' -f1)
          WSUM=$(sha256sum "$WASM" | cut -d' ' -f1)
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          cat > dist/version.json <<JSON
          {
            "mujocoVersion": "${MJVER}",
            "emscripten": "${EMVER}",
            "buildTime": "${NOW}",
            "gitSha": "${MJ_SHA}",
            "features": {"qhulloff": true, "render": false, "plugins": false, "libccd": "static"},
            "size": {"wasmBytes": ${WSB}, "jsBytes": ${JSB}},
            "hash": {"wasmSha256": "${WSUM}", "jsSha256": "${JSUM}"}
          }
          JSON

      - name: Generate SBOM (SPDX json)
        shell: bash
        run: |
          set -euxo pipefail
          EMVER=3.1.55
          MJVER=3.3.7
          MJ_SHA=$(git -C external/mujoco rev-parse HEAD)
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          NS="https://github.com/lshdlut/mujoco-wasm-forge/sbom/${GITHUB_RUN_ID}"
          cat > dist/sbom.spdx.json <<SBOM
          {
            "spdxVersion": "SPDX-2.3",
            "dataLicense": "CC0-1.0",
            "SPDXID": "SPDXRef-DOCUMENT",
            "name": "mujoco-wasm-forge-${MJVER}",
            "documentNamespace": "${NS}",
            "creationInfo": {"created": "${NOW}", "creators": ["Tool: forge-337 workflow"]},
            "packages": [
              {"name": "mujoco", "SPDXID": "SPDXRef-Pkg-MuJoCo", "versionInfo": "${MJVER}", "downloadLocation": "https://github.com/google-deepmind/mujoco", "sourceInfo": "git@${MJ_SHA}"},
              {"name": "emscripten", "SPDXID": "SPDXRef-Pkg-Emscripten", "versionInfo": "${EMVER}", "downloadLocation": "https://github.com/emscripten-core/emsdk"}
            ]
          }
          SBOM

      - name: Generate checksums and release notes
        shell: bash
        run: |
          set -euxo pipefail
          EMVER=3.1.55
          MJVER=3.3.7
          JS=dist/mujoco-${MJVER}.js; WASM=dist/mujoco-${MJVER}.wasm
          JSB=$(stat -c %s "$JS") || JSB=0
          WSB=$(stat -c %s "$WASM") || WSB=0
          JSUM=$(sha256sum "$JS" | cut -d' ' -f1)
          WSUM=$(sha256sum "$WASM" | cut -d' ' -f1)
          {
            echo "$JSUM  $(basename "$JS")"
            echo "$WSUM  $(basename "$WASM")"
          } > dist/SHA256SUMS.txt
          cat > dist/RELEASE_NOTES.md <<EOF
          MuJoCo ${MJVER} WASM r1

          Toolchain
          - Emscripten: ${EMVER}
          - Node: 20

          Artifacts
          - mujoco-${MJVER}.js (${JSB} bytes), sha256=${JSUM}
          - mujoco-${MJVER}.wasm (${WSB} bytes), sha256=${WSUM}
          - version.json, sbom.spdx.json, SHA256SUMS.txt

          Tests
          - Smoke (Node): minimal pendulum, 200 steps, finite checks
          - Regression: WASM vs native harness (see workflow logs)

          Notes
          - ES module factory: createMuJoCo; runtime methods: cwrap/ccall
          - Exports: _mjw_init,_mjw_step_demo,_mjw_nq,_mjw_qpos0,_mjw_qvel0,_mjw_term,_malloc,_free
          EOF

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mujoco-3.3.7
          path: dist/

      - name: Quality gates (size + init time)
        shell: bash
        env:
          QUALITY_ENFORCE: '0'
          WASM_MAX_BYTES: '16000000'
          JS_MAX_BYTES: '2000000'
          MAX_INIT_MS: '8000'
        run: node tests/gates-337.mjs

      - name: Create Release (optional)
        if: ${{ startsWith(github.ref, 'refs/tags/forge-3.3.7-') || (github.event_name == 'workflow_dispatch' && inputs.publish == 'true') }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'forge-3.3.7-r1' }}
          name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'MuJoCo 3.3.7 WASM r1' }}
          body_path: dist/RELEASE_NOTES.md
          draft: false
          prerelease: ${{ contains(github.ref, '-rc.') }}
          files: |
            dist/mujoco-3.3.7.js
            dist/mujoco-3.3.7.wasm
            dist/version.json
            dist/sbom.spdx.json
            dist/SHA256SUMS.txt
